{
 "title": "E_commerce monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Revenue (last hour)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT revenue, profit, time FROM revenue ORDER BY time"
    }
   ]
  },
  {
   "title": "Checkout clicks count (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT source, SUM(count) AS count\nFROM source_count\nWHERE time >= now() -  INTERVAL '1 hour'\nGROUP BY source\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Most popular products (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT category, SUM(count) AS count\nFROM category_count\nWHERE time >= now() -  INTERVAL '1 hour'\nGROUP BY category\nORDER BY count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Customer's gender distribution (last hour)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT gender, SUM(count)\nFROM gender_count\nWHERE time >= now() - INTERVAL '1 hour'\nGROUP BY (gender)\n\n"
    }
   ]
  },
  {
   "title": "Fail payment (last hour)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT description, SUM(count) AS count\nFROM fail_count\nWHERE time >= now() -  INTERVAL '1 hour'\nGROUP BY description\nORDER BY count DESC"
    }
   ]
  }
 ]
}